### ISSUE TITLE
Toggle the commentary

### ISSUE THREAD

**Issue by philderbeast** [cabalism/updo#14]
Can we have an option for toggling the commentary in the generated stack.yaml?

All the `# ...` comments here are generated, from up-do/dex-lang@062c46a.

```
# We have 1 packages.
packages:
  - ./.

# We have 1 source packages listed in this order:
#   * external 1
#   * internal 0
#   * external forks 0
#   * internal forks 0
extra-deps:

  # Source Packages, external (3rd party).
  - git: https://github.com/llvm-hs/llvm-hs
    commit: 423220bffac4990d019fc088c46c5f25310d5a33
    subdirs:
      - llvm-hs
      - llvm-hs-pure

  # Source Packages, internal to this organisation (private and public).

  # Source Packages, external (3rd party) forks of other repositories.
  # Can we help upstream?

  # Source Packages, internal forks of other repositories.
  # Can we upstream and unfork?

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - floating-bits-0.3.0.0
  - megaparsec-8.0.0
  - prettyprinter-1.6.2
  - store-0.7.8
  - store-core-0.4.4.4
  - th-utilities-0.2.4.1
  ```
