### ISSUE TITLE
Don't leave dangling comment about version equality constraints

### ISSUE THREAD

**Issue by philderbeast** [cabalism/updo#28]
Don't add a comment about version equality constraints when there are none, such as for `persistent`:

```
import: https://stackage.org/nightly-2023-12-05/cabal.config

-- We have 8 packages.
packages:
    persistent
  , persistent-mongoDB
  , persistent-mysql
  , persistent-postgresql
  , persistent-qq
  , persistent-redis
  , persistent-sqlite
  , persistent-test

-- Version equality constraints.

program-options
  ghc-options: -fhide-source-paths
  ```

**Comment by philderbeast** [comment]
Same goes for `dhall2stack`, not a comment but instead a dangling empty `extra-deps`:

```yaml
user-message: "WARNING: This stack project is generated."

resolver: nightly-2024-05-18

# We have 4 packages.
packages:
  - ./hledger
  - ./hledger-lib
  - ./hledger-ui
  - ./hledger-web

extra-deps: []
```
